export const projectsList = [
   {
      desk: "/webimg/h_ageofemotions.png",
      phone: "/webimg/v_ageofemotions.png",
      photoURL: "/webimg/ageofemotions.png",
      link: "https://www.ageofemotions.com/",
      github: "https://github.com/agredo-alejo/amayliberate",
      title: "Age Of Emotions",
      techs: ["NextJs", "MailerLite", "Stripe", "Tyescript", "TailwindCss"],
   },
   {
      desk: "/webimg/h_jiyaki.png",
      phone: "/webimg/v_jiyaki.png",
      photoURL: "/webimg/jiyaki.png",
      link: "https://jiyaki.web.app/",
      github: "https://github.com/agredo-alejo/jiyaki",
      title: "Jiyaki",
      techs: ["React", "Tyescript", "Sass", "Firebase"],
   },
   {
      desk: "/webimg/h_chat.png",
      phone: "/webimg/v_chat.png",
      photoURL: "/webimg/apollochat.png",
      link: "https://apollochat.vercel.app/",
      github: "https://github.com/agredo-alejo/apollochat",
      title: "Apollo Chat",
      techs: ["NextJs", "Tyescript", "TailwindCss", "Firebase"],
   },
   {
      desk: "/webimg/h_inventory.png",
      phone: "/webimg/v_inventory.png",
      photoURL: "/webimg/inventory.png",
      link: "https://products-inventory-275.web.app/stats",
      github: "https://github.com/agredo-alejo/products-inventory",
      title: "Inventory Management",
      techs: ["React", "Tyescript", "Sass", "Firebase"],
   },
];
